name: 'Lint Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Print working directory
        run: pwd

      - name: Run Linter
        run: |
          pwd
          find . -name "*.py" -exec flake8 {} +
          echo "Linted all the python files successfully"

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ensure you're using Node.js 16 or above

      - name: Install ESLint and plugins
        run: |
          npm install eslint@latest eslint-plugin-react --save-dev

      - name: Run ESLint Linter
        run: |
          npx eslint ./server/database ./server/frontend/src --ext .js,.jsx
          echo "Linted all the JS files successfully"
