  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install JSHint
        run: npm install jshint --global

      - name: Add JSHint Configuration to Files
        run: |
          # Find all JavaScript files and prepend the JSHint directive
          find ./server/database ./server/frontend/src -name "*.js" -exec sh -c 'echo "/*jshint esversion: 8 */" | cat - {} > temp && mv temp {}' \;
          echo "Added JSHint esversion: 8 directive to all JS files"

      - name: Run Linter
        run: |
          # Find and lint all JavaScript files
          find ./server/database ./server/frontend/src -name "*.js" -exec jshint {} +
          echo "Linted all the js files successfully"
